import "../globals.css";
import { manrope, denton } from "../fonts/font";
import DashNav from "@/components/DashNav";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${denton.variable} ${manrope.variable} antialiased`}>
        {children}
        <DashNav />
      </body>
    </html>
  );
}
